### ISSUE TITLE
Replace Datscan with stardox.

### ISSUE THREAD

**Issue by 0xPrateek** [DevelopedByAnurag/Datscan#1]
Hello,
In your readme please update:: 
`Starting Stardox :
cd Datscan/src
python3 Datscan.py
Example Usage : `python3 ./Datscan.py`

with...
`Starting Datscan:
cd Datscan/src
python3 Datscan.py
Example Usage : `python3 ./Datscan.py`

**Comment by DevelopedByAnurag** [comment]
Thank you bro for reporting it . We have updated it ..
