### ISSUE TITLE
Follow PEP8 and other good practices guides for coding

### ISSUE THREAD

**Issue by c0x6a** [DevelopedByAnurag/Datscan#5]
Stop using UPPERCASE and l33t to write code, for the sake of humanity; follow good practices for coding, apply clean code concepts, at least read the PEP-8.

Thanks :)

**Comment by DevelopedByAnurag** [comment]
It's simply an irrelevant Issue as using upper case and l33t to code is perfectly okay and name of variables can be anything No matters it contains a Number or is caps it will work completely same as a variable. 

Also,  usage of l33t was a need as without it chances of usage  same named variables by modules (developed by others) might increase and result in breaking of the program.

**Comment by DevelopedByAnurag** [comment]
Hey, this issue has been resolved and you can see this within the next 72 hr in our next Update.... The beauty of Opensource is public readable code with the ability for everyone to modify it and I realized my mistake as Everyone can't understand l33t that's why I have resolved this Issue
